'use strict';
const $=id=>document.getElementById(id),KEY='kejian-courses-v3',FIRST_MONDAY='2026-09-07',DAY=86400000;
const defaultCourses=[
{id:'english',name:'学硕英二班英语',teacher:'王晔',room:'文昌楼224',type:1,first:2,last:19,people:164,span:1,meet:[[0,1,'10:10','11:50'],[1,0,'08:00','09:40']]},
{id:'world',name:'2026级中国史世界史世界史基本问题研究',teacher:'赵冠峰',room:'文昌楼124',type:0,first:2,last:19,people:22,span:1,meet:[[1,1,'10:10','11:50']]},
{id:'method',name:'2026级中国史世界史史学理论与方法',teacher:'王记录',room:'文昌楼124',type:0,first:2,last:19,people:22,span:1,meet:[[0,3,'16:40','18:20']]},
{id:'frontier',name:'2026级中国史世界史中国史理论与学术前沿',teacher:'杨翔宇',room:'文昌楼124',type:0,first:2,last:19,people:22,span:1,meet:[[2,4,'19:30','21:10']]},
{id:'socialism',name:'文科二班（中特）新时代中国特色社会主义理论与实践（学硕）',teacher:'姚广利',room:'文昌楼224',type:1,first:2,last:13,people:180,span:2,meet:[[4,2,'14:30','17:25']]},
{id:'marx',name:'学硕文科二班马克思主义与社会科学方法论',teacher:'刘巧凤',room:'文昌楼224',type:1,first:14,last:19,people:161,span:2,meet:[[4,2,'','']]}
];
const periods=[['上午','1–2节'],['上午','3–4节'],['下午','1–2节'],['下午','3–4节'],['晚上','1–2节'],['晚上','3–5节']],timeDefaults=[['08:00','09:40'],['10:10','11:50'],['14:30',''],['16:40','18:20'],['19:30','21:10'],['','']],days=['一','二','三','四','五','六','日'];
const colors=[['#eaf0e4','#91a780'],['#e9f0f4','#8ba5b6']],labels=['专业课程','公共课程'];
let courses=structuredClone(defaultCourses),editing=null,dirtyCalendar=false;
const semester=Date.parse(FIRST_MONDAY+'T00:00:00+08:00');
function currentWeek(){return Math.max(1,Math.min(19,Math.floor((Date.now()-semester)/(7*DAY))+1))}
let selected=currentWeek();
try{const data=JSON.parse(localStorage.getItem(KEY));if(data&&Array.isArray(data.courses)&&data.courses.every(validCourse)){courses=data.courses;dirtyCalendar=!!data.dirtyCalendar}}catch{message('未能读取保存数据，当前显示原始课表。')}
function validCourse(c){return c&&typeof c.id==='string'&&typeof c.name==='string'&&typeof c.teacher==='string'&&typeof c.room==='string'&&[0,1].includes(c.type)&&Number.isInteger(c.first)&&Number.isInteger(c.last)&&c.first>=2&&c.last<=19&&c.first<=c.last&&[1,2].includes(c.span)&&Array.isArray(c.meet)&&c.meet.length>0&&c.meet.every(m=>Array.isArray(m)&&Number.isInteger(m[0])&&m[0]>=0&&m[0]<=6&&Number.isInteger(m[1])&&m[1]>=0&&m[1]+c.span<=6&&typeof m[2]==='string'&&typeof m[3]==='string')}
function message(text){$('feedback').textContent=text}
function persist(next){try{localStorage.setItem(KEY,JSON.stringify({courses:next,dirtyCalendar:true}));courses=next;dirtyCalendar=true;render();message('已保存在当前设备。已导入的日历不会自动同步，请更新日历提醒。');return true}catch{message('保存失败：设备存储不可用或已满，修改未保存。');return false}}
function dateText(ms){return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric'}).format(ms)}
function slotText(c,s){return periods[s][0]+' '+(c.span===2?(c.id==='socialism'?'1–3节':'跨两时段'):periods[s][1])}
function render(){const active=courses.filter(c=>selected>=c.first&&selected<=c.last);$('week').value=selected;$('prev').disabled=selected===1;$('next').disabled=selected===19;const base=semester+(selected-1)*7*DAY;$('summary').textContent='第 '+selected+' 周 · '+dateText(base)+'–'+dateText(base+6*DAY)+' · '+active.reduce((n,c)=>n+c.meet.length,0)+' 次课'+(selected===1?' · 第1周不上课':'');$('calendar-warning').textContent=dirtyCalendar?'课程已修改：如已导入手机日历，请先移除旧课表日历，再导入新的提醒文件。':'修改仅保存在当前设备。清除浏览器数据会丢失修改。';const grid=$('grid');grid.replaceChildren();const blank=document.createElement('div');blank.className='day';blank.textContent='节次';grid.append(blank);days.forEach((d,i)=>{const el=document.createElement('div');el.className='day';el.textContent='星期'+d;const small=document.createElement('small');small.textContent=dateText(base+i*DAY);el.append(small);grid.append(el)});periods.forEach((p,s)=>{const time=document.createElement('div');time.className='slot time';time.style.gridColumn='1';time.style.gridRow=String(s+2);time.innerHTML='<strong>'+p[0]+'</strong>'+p[1];grid.append(time);for(let d=0;d<7;d++){const covering=active.filter(c=>c.span===2&&c.meet.some(m=>m[0]===d&&m[1]+1===s));const here=active.filter(c=>c.meet.some(m=>m[0]===d&&m[1]===s));if(covering.length&&!here.length)continue;const cell=document.createElement('div');cell.className='slot';cell.style.gridColumn=String(d+2);cell.style.gridRow=String(s+2);if(here.length){const span=Math.max(...here.map(c=>c.span));cell.style.gridRow=(s+2)+' / span '+span;here.forEach(c=>{const m=c.meet.find(m=>m[0]===d&&m[1]===s);const b=document.createElement('button');b.className='course';b.style.setProperty('--bg',colors[c.type][0]);b.style.setProperty('--accent',colors[c.type][1]);const title=document.createElement('b');title.textContent=c.name;const place=document.createElement('span');place.textContent=c.room;const teacher=document.createElement('em');teacher.textContent=c.teacher+' · '+c.first+'–'+c.last+'周';const clock=document.createElement('span');clock.textContent=m[2]&&m[3]?m[2]+'–'+m[3]:'钟点待补充';b.append(title,place,teacher,clock);b.onclick=()=>openDetail(c,m);cell.append(b)})}else cell.innerHTML='<div class="empty" aria-label="无课程">·</div>';grid.append(cell)}})}
function openDetail(c,m){$('title').textContent=c.name;$('type').textContent=labels[c.type];$('info').replaceChildren();[['任课教师',c.teacher],['上课地点',c.room],['上课节次','星期'+days[m[0]]+' · '+slotText(c,m[1])],['上课钟点',m[2]&&m[3]?m[2]+'–'+m[3]:'待补充'],['教学周次','第 '+c.first+'–'+c.last+' 周（连续周）'],['上课人数',c.people+'人']].forEach(([k,v])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;$('info').append(dt,dd)});$('desc').textContent='第2周从2026年9月14日开始。点击编辑可修改这门课程的全部上课安排。';$('edit-course').onclick=()=>{$('detail').close();openEditor(c)};$('delete-course').onclick=()=>{if(confirm('删除“'+c.name+'”？修改仅影响当前设备。')){if(persist(courses.filter(x=>x.id!==c.id)))$('detail').close()}};$('detail').showModal()}
function addMeeting(m=[0,0,'08:00','09:40']){const row=document.createElement('fieldset');row.className='meeting-row';row.innerHTML='<legend>上课安排</legend><label>星期<select class="meeting-day">'+days.map((d,i)=>'<option value="'+i+'">星期'+d+'</option>').join('')+'</select></label><label>课表位置<select class="meeting-slot">'+periods.map((p,i)=>'<option value="'+i+'">'+p.join(' ')+'</option>').join('')+'</select></label><label>开始<input class="meeting-start" type="time"></label><label>结束<input class="meeting-end" type="time"></label><button type="button" class="remove-meeting">移除此安排</button>';
row.querySelector('.meeting-day').value=m[0];row.querySelector('.meeting-slot').value=m[1];row.querySelector('.meeting-start').value=m[2];row.querySelector('.meeting-end').value=m[3];row.querySelector('.remove-meeting').onclick=()=>row.remove();row.querySelector('.meeting-slot').onchange=e=>{const t=timeDefaults[Number(e.target.value)];row.querySelector('.meeting-start').value=t[0];row.querySelector('.meeting-end').value=t[1]};$('meetings').append(row)}
function openEditor(c){editing=c?.id||null;$('editor-title').textContent=c?'编辑课程':'添加课程';$('course-form').reset();$('course-name').value=c?.name||'';$('course-teacher').value=c?.teacher||'';$('course-room').value=c?.room||'';$('course-type').value=c?.type??0;$('course-first').value=c?.first??2;$('course-last').value=c?.last??19;$('course-people').value=c?.people??0;$('course-span').value=c?.span??1;$('meetings').replaceChildren();(c?.meet||[[0,0,'08:00','09:40']]).forEach(addMeeting);$('form-error').textContent='';$('editor').showModal()}
$('course-form').onsubmit=e=>{e.preventDefault();const meet=Array.from($('meetings').children).map(row=>[Number(row.querySelector('.meeting-day').value),Number(row.querySelector('.meeting-slot').value),row.querySelector('.meeting-start').value,row.querySelector('.meeting-end').value]);const c={id:editing||('local-'+crypto.randomUUID()),name:$('course-name').value.trim(),teacher:$('course-teacher').value.trim(),room:$('course-room').value.trim(),type:Number($('course-type').value),first:Number($('course-first').value),last:Number($('course-last').value),people:Number($('course-people').value),span:Number($('course-span').value),meet};let error='';if(!c.name||!validCourse(c))error='请填写课程名称、有效周次和至少一条上课安排。';else if(meet.some(m=>(m[2]&&!m[3])||(!m[2]&&m[3])||(m[2]&&m[3]&&m[2]>=m[3])))error='每条安排请同时填写开始、结束时间，结束必须晚于开始；也可都留空。';else if(new Set(meet.map(m=>m[0]+'-'+m[1])).size!==meet.length)error='同一课程的上课位置不能重复。';else if(courses.some(other=>other.id!==c.id&&other.first<=c.last&&other.last>=c.first&&other.meet.some(a=>meet.some(b=>a[0]===b[0]&&a[1]<b[1]+c.span&&b[1]<a[1]+other.span))))error='该周次和时段与已有课程重叠，请调整安排。';if(error){$('form-error').textContent=error;return}const next=editing?courses.map(x=>x.id===editing?c:x):[...courses,c];if(persist(next))$('editor').close()};
for(let i=1;i<=19;i++)$('week').add(new Option('第 '+i+' 周',i));$('week').onchange=e=>{selected=Number(e.target.value);render()};$('prev').onclick=()=>{if(selected>1){selected--;render()}};$('next').onclick=()=>{if(selected<19){selected++;render()}};$('current').onclick=()=>{selected=currentWeek();render()};$('close').onclick=()=>$('detail').close();$('add-course').onclick=()=>openEditor();$('close-editor').onclick=()=>$('editor').close();$('add-meeting').onclick=()=>addMeeting();
function escapeICS(value){return String(value).replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,')}
function utcStamp(ms){return new Date(ms).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z')}
function meetingDate(week,day,time){return semester+((week-1)*7+day)*DAY+(Number(time.slice(0,2))*60+Number(time.slice(3)))*60000}
function foldICS(line){let out='',size=0;for(const ch of line){const bytes=new TextEncoder().encode(ch).length;if(size+bytes>73){out+='\r\n ';size=1}out+=ch;size+=bytes}return out}
function calendarText(){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Kejian//Course Schedule//ZH','CALSCALE:GREGORIAN','METHOD:PUBLISH','X-WR-CALNAME:课间课程提醒'];let count=0,missing=new Set();const now=Date.now();for(const c of courses)for(let w=c.first;w<=c.last;w++)for(const m of c.meet){if(!m[2]||!m[3]){missing.add(c.name);continue}const start=meetingDate(w,m[0],m[2]),end=meetingDate(w,m[0],m[3]);if(end<=now)continue;const uid=c.id+'-'+w+'-'+m[0]+'-'+m[1]+'@kejian.local';lines.push('BEGIN:VEVENT','UID:'+escapeICS(uid),'DTSTAMP:'+utcStamp(now),'DTSTART:'+utcStamp(start),'DTEND:'+utcStamp(end),'SUMMARY:'+escapeICS(c.name),'LOCATION:'+escapeICS(c.room),'DESCRIPTION:'+escapeICS('第'+w+'周；教师：'+c.teacher+'；北京时间。修改App课程不会同步更新此日历。'),'BEGIN:VALARM','TRIGGER:-PT10M','ACTION:DISPLAY','DESCRIPTION:'+escapeICS('10分钟后上课：'+c.name+'，'+c.room),'END:VALARM','END:VEVENT');count++}lines.push('END:VCALENDAR');return {text:lines.map(foldICS).join('\r\n')+'\r\n',count,missing:[...missing]}}
function downloadText(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
$('reminders').onclick=()=>$('reminder-guide').showModal();$('close-reminders').onclick=()=>$('reminder-guide').close();$('export-calendar').onclick=()=>{const result=calendarText();if(!result.count){$('export-status').textContent='没有可导出的未来课程，请补充上课钟点。';return}downloadText('课间-课程提醒.ics',result.text,'text/calendar;charset=utf-8');$('export-status').textContent='已导出 '+result.count+' 次未来课程，课前10分钟提醒。'+(result.missing.length?'以下课程钟点未补齐，未导出：'+result.missing.join('、')+'。':'')+'请导入日历后检查一条课程的通知设置。'};
render();
